name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        default: 'conan-io/conan-center-index'
      ref:
        required: true
        default: 'master'
      path:
        required: true
        default: 'recipes/qt/6.x.x'
      version:
        required: true
        default: '6.5.1'

jobs:
  _:
    name: "${{ github.event.inputs.repository }} ${{ github.event.inputs.ref }} ${{ github.event.inputs.path }} ${{ github.event.inputs.version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]
        shared: ["True", "False"]
    continue-on-error: true
    env:
      NOT_ON_C3I: 1
    steps:    
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: pip3 install conan yq

      - if: ${{ runner.os == 'Windows' }}
        run: echo "CONAN_HOME=${{ runner.temp }}\\.c2" >> "$GITHUB_ENV"
        
      - run: conan profile detect --force
        shell: bash
          
      - name: List cppstds
        shell: bash
        run: |
          PROFILE_PATH=$(conan profile path default)
          COMPILER=$(awk -F "=" '/^compiler=/ {print $2}' $PROFILE_PATH)
          COMPILER_VERSION=$(awk -F "=" '/^compiler.version=/ {print $2}' $PROFILE_PATH)
          echo "$PROFILE_PATH $COMPILER $COMPILER_VERSION"
          CPP_STDS=$(curl https://github.com/conan-io/conan-center-index/raw/master/.c3i/config_v2.yml -L | yq -r -c .cppstd.\"$COMPILER\".\"$COMPILER_VERSION\"[])
          echo "CPP_STDS=$CPP_STDS" >> "$GITHUB_ENV"
          
      - name: conan create
        shell: bash
        env:
          CONAN_SYSREQUIRES_MODE: enabled
        run: |
          for cpp_std in $CPP_STDS; do
              cpp_std=$(echo $cpp_std | tr -d '[:space:]')
              code=0
              set +o pipefail
              conan create -s compiler.cppstd=$cpp_std --version ${{ github.event.inputs.version }} --build=missing ${{ github.event.inputs.path }} -o */*:shared=${{ matrix.shared }} -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True || code=$?
              echo $code
              if [ $code -ne 6 ]; then
                  break
              fi
          done
          exit "$code"
